### ISSUE TITLE
Dropdown caret gets hidden due to overarching border style directive

### ISSUE THREAD

**Issue by ilyvion** [Questionable-Content-Extensions/client#16]
The down arrow/caret gets hidden due to this style rule:

```css
#qcnav_navbox * {
    border: none;
}
```

This is because the caret is drawn using CSS `border`. Find a way to make unwanted borders disappear without targeting wanted ones.
